name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
        working-directory: api
      - run: npm run build
        working-directory: api
      - run: ls -ltr
        working-directory: api
      - run: |
          echo @sergeyfilyanin:https://npm.pkg.github.com/ > api/build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> api/build/.npmrc
      - run: npm publish
        working-directory: api/build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
