name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:
  publish-to-latest-relase:

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: api
        run: yarn install

      - name: Build @gear-js/api
        working-directory: api
        run: yarn build
        
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: latest
          draft: true
          prerelease: false

      - name: Publish
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: api/lib
          asset_name: my-artifact.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
