name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
        working-directory: api
      - run: npm run build
        working-directory: api
      - run: ls -ltr
        working-directory: api
      - name: Set package registry
        run: npm config set registry https://npm.pkg.github.com
      - name: GitHub package registry authentication
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GPR_TOKEN }}
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }
#      - run: |
#          echo @sergeyfilyanin:https://npm.pkg.github.com/ > api/lib/.npmrc
#          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> api/lib/.npmrc
      - run: npm publish
        working-directory: api/lib
        env:
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
