name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:
  publish-to-latest-relase:


    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Use node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: api
        run: yarn install

      - name: Build @gear-js/api
        working-directory: api
        run: yarn build

      - name: Publish
        working-directory: api/lib
        run: |
          npm config set registry "https://npm.pkg.github.com"
          npm publish
        env:
          token: ${{secrets.GITHUB_TOKEN}}
