name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:
  publish-to-latest-relase:


    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Use node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        working-directory: api
        run: yarn install

      - name: Build @gear-js/api
        working-directory: api
        run: yarn build
      - run: |
          echo @sergeyfilyanin:https://npm.pkg.github.com/ > build/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
      - run: npm publish
        working-directory: ./build
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
