name: 'CI-CD @gear-js/api'

on:
  workflow_dispatch:

jobs:
  publish-to-latest-relase:


    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
        working-directory: api
      - run: yarn build
        working-directory: api
      - run: npm publish
        working-directory: api
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
